### PR TITLE
config draft

### PR DESCRIPTION
**Pull request by fvovan**

### CODE REVIEW

**Comment by fvovan** [comment]
@vogdb please review,
not sure about logging best practises , I mean place where to store log file.

**Comment by vogdb** [comment]
@fvovan Looks ok but lets wrap log functionality into a separate class!

**Comment by fvovan** [comment]
@vogdb did it, but still not sure how is better to setup log file path.

**Comment by vogdb** [comment]
Lets use camel case in config where the first letter starts from in lower case.

**Comment by vogdb** [comment]
please fix the config letter case in its usages.

**Pull request merged**
